// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const rooms = sqliteTable("rooms", {
	id: integer().primaryKey({ autoIncrement: true }),
	code: text().notNull(),
	status: text().default("lobby"),
	mode: text().default("infiltrator"),
	currentTurnPlayerId: integer("current_turn_player_id"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	options: text(),
},
(table) => [
	index("idx_rooms_code").on(table.code),
]);

export const players = sqliteTable("players", {
	id: integer().primaryKey({ autoIncrement: true }),
	roomId: integer("room_id").notNull().references(() => rooms.id, { onDelete: "cascade" } ),
	name: text().notNull(),
	role: text(),
	word: text(),
	isAlive: integer("is_alive").default(1),
	votes: integer().default(0),
	isHost: integer("is_host").default(0),
	lastSeen: integer("last_seen").default(sql`(unixepoch())`),
	clue: text(),
},
(table) => [
	index("idx_players_room_id").on(table.roomId),
]);

